import type { Category } from './categories'
import { standardPricing, standardProcess } from './categories'

export const SEO_LANDING_PAGES: Category[] = [
  {
    slug: 'activewear-manufacturer-china',
    h1: 'Custom Activewear Manufacturer in China for Emerging Brands',
    metaTitle: 'Custom Activewear Manufacturer China | Low MOQ 50pcs | ClothReady',
    metaDesc: 'Looking for a custom activewear manufacturer in China? ClothReady produces leggings, sports bras, and gym sets with MOQ 50pcs, fast sampling, and full private label service.',
    intro: 'ClothReady is a custom activewear manufacturer based in Dongguan, China — the largest apparel manufacturing hub in the country. We produce leggings, sports bras, training tops, joggers, and matching sets for fitness and activewear brands worldwide, with a minimum order quantity of just 50 pieces per style per color.',
    intro2: "If you're searching for a China-based activewear factory that won't force you into 500+ piece minimums, ClothReady is built for exactly that. We work directly with founders — no trading company markup, no middleman — from tech pack review through bulk production and shipping.",
    keyPoints: [
      'Direct factory, no trading company markup',
      'MOQ 50 pieces per style per color',
      'Performance fabrics: nylon/spandex, moisture-wicking poly blends',
      'English-speaking team, fast WhatsApp response',
    ],
    whatWeMake: [
      { name: 'Leggings & Yoga Pants', moq: '50 pcs/color' },
      { name: 'Sports Bras & Crop Tops', moq: '50 pcs/color' },
      { name: 'Training Tees & Tanks', moq: '50 pcs/color' },
      { name: 'Joggers & Track Pants', moq: '50 pcs/color' },
      { name: 'Matching Activewear Sets', moq: '50 sets/color' },
      { name: 'Windbreakers & Light Jackets', moq: '100 pcs/color' },
    ],
    fabrics: [
      { name: 'Nylon/Spandex (80/20)', spec: '4-way stretch, 200–230gsm', use: 'Leggings, sports bras, shorts' },
      { name: 'Polyester/Spandex (88/12)', spec: 'Moisture-wicking, 180–210gsm', use: 'Training tees, tanks, sets' },
      { name: 'Recycled REPREVE® Nylon', spec: 'GRS certified, 200–220gsm', use: 'Sustainable activewear lines' },
      { name: 'Ribbed Seamless Knit', spec: '4-way stretch, 220–260gsm', use: 'Matching sets, bodysuits' },
    ],
    pricing: standardPricing,
    process: standardProcess('activewear'),
    why: [
      { title: 'Located in China\'s Apparel Capital', desc: 'Dongguan gives us direct access to fabric mills, trims, and skilled sewing labor — faster sampling and better pricing than sourcing agencies.' },
      { title: 'Low MOQ — Start at 50 Pcs', desc: 'Launch or test a new activewear line without the overstock risk of factories requiring 500–1000 piece minimums.' },
      { title: 'Full Private Label', desc: 'Woven labels, hang tags, custom packaging, and branded polybags — your brand, not ours, on every piece.' },
      { title: 'Direct Factory Pricing', desc: 'No trading company markup. You work directly with our production team from quote to shipment.' },
    ],
    faqs: [
      { q: 'Why source activewear manufacturing from China specifically?', a: 'China — and Dongguan in particular — has the deepest supply chain for performance fabrics, elastic trims, and technical sewing skills, which keeps both quality and cost competitive compared to most other regions.' },
      { q: 'What is your MOQ for custom activewear?', a: '50 pieces per style per color. This applies across leggings, sports bras, tops, and sets.' },
      { q: 'Do you work with brands outside the US and Europe?', a: 'Yes, we ship worldwide via air or sea freight and work with brands across North America, Europe, Australia, and the Middle East.' },
      { q: 'Can you match an existing activewear sample or reference photo?', a: 'Yes. Send us a reference sample or clear photos and spec sheet, and our pattern team will replicate fit and construction as closely as possible.' },
      { q: 'How is ClothReady different from a sourcing agent?', a: "We are the factory — not a middleman. You work directly with our production floor, which means faster communication, no markup, and full visibility into your order." },
    ],
    products: [
      { id: 'activewear-set', name: 'Matching Activewear Set', img: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80', tag: 'Full Set' },
      { id: 'highwaist-leggings', name: 'High-Waist Leggings', img: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&q=80', tag: 'Squat-Proof' },
      { id: 'racerback-sports-bra', name: 'Racerback Sports Bra', img: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=600&q=80', tag: 'Medium Impact' },
      { id: 'training-shorts', name: 'Training Shorts', img: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80', tag: 'MOQ 50' },
    ],
    relatedCategories: ['gym-wear-manufacturer', 'yoga-pants-manufacturer', 'sports-bra-manufacturer'],
    ctaText: 'Get an Activewear Quote',
  },
  {
    slug: 'private-label-gym-wear',
    h1: 'Private Label Gym Wear Supplier — Your Brand, Our Factory',
    metaTitle: 'Private Label Gym Wear Supplier | Custom Branding, MOQ 50pcs',
    metaDesc: 'ClothReady is a private label gym wear supplier in China. Custom woven labels, hang tags, and packaging on leggings, sports bras & sets. MOQ 50pcs.',
    intro: "ClothReady is a private label gym wear supplier — every piece we produce ships with your brand's woven labels, hang tags, and packaging, never ours. We specialize in helping fitness and activewear brands go from concept to a fully branded product line without owning a factory.",
    intro2: "Private label means you're not just buying blank stock — you're building a distinct product with your logo, your care labels, your color story, and your packaging. Our team handles the entire branding layer alongside garment production, so what arrives at your warehouse is retail-ready.",
    keyPoints: [
      'Woven labels, care tags & hang tags included',
      'Custom colorways matched to your brand palette',
      'Branded polybags & retail-ready packaging',
      'MOQ 50 pieces per style — ideal for private label testing',
    ],
    whatWeMake: [
      { name: 'Private Label Leggings', moq: '50 pcs/color' },
      { name: 'Private Label Sports Bras', moq: '50 pcs/color' },
      { name: 'Private Label Gym Tops & Tanks', moq: '50 pcs/color' },
      { name: 'Private Label Hoodies & Sweats', moq: '50 pcs/color' },
      { name: 'Private Label Matching Sets', moq: '50 sets/color' },
    ],
    fabrics: [
      { name: 'Nylon/Spandex (80/20)', spec: '4-way stretch, 200–230gsm', use: 'Leggings, sports bras, shorts' },
      { name: 'Polyester/Spandex (88/12)', spec: 'Moisture-wicking, 180–210gsm', use: 'Training tees, tanks' },
      { name: 'Cotton/Polyester Fleece', spec: '280–380gsm', use: 'Hoodies, sweatshirts, warm-ups' },
    ],
    pricing: standardPricing,
    process: standardProcess('private label gym wear'),
    why: [
      { title: 'Branding Built Into Production', desc: "Labels, tags, and packaging are planned alongside the garment — not bolted on afterward — so your brand identity is consistent from fabric to final pack." },
      { title: 'Low MOQ for Testing New SKUs', desc: 'Trial a new private label style at 50 pieces before committing to a full production run.' },
      { title: 'Design Support Included', desc: "No formal tech pack? We help translate a reference sample or sketch into a production-ready spec sheet." },
      { title: 'Consistent Color Matching', desc: 'We use Pantone-matched dye lots so your private label colorway stays consistent across reorders.' },
    ],
    faqs: [
      { q: 'What does "private label" actually include?', a: 'Your custom woven or printed labels, care/size tags, hang tags, and packaging (polybags, boxes, or branded mailers) — all applied during production, not after.' },
      { q: 'Do I need my own tech pack to start?', a: "No. We can work from a reference sample, sketch, or even a competitor product photo, and our pattern team will build a spec sheet for you." },
      { q: 'What is the MOQ for private label gym wear?', a: '50 pieces per style per color — one of the lowest MOQs available for fully private-labeled activewear.' },
      { q: 'Can you match my brand\'s exact color?', a: 'Yes, we work from Pantone codes or physical swatches to match your brand colors as closely as fabric dye allows.' },
      { q: 'How long until my first private label order ships?', a: 'Samples in 7–10 business days, then 25–35 business days for bulk production after sample approval.' },
    ],
    products: [
      { id: 'racerback-sports-bra-pl', name: 'Private Label Sports Bra', img: 'https://images.unsplash.com/photo-1554284126-aa88f22d8b74?w=600&q=80', tag: 'Custom Label' },
      { id: 'gym-full-set-pl', name: 'Private Label Training Set', img: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80', tag: 'Full Set' },
      { id: 'seamless-leggings-pl', name: 'Private Label Leggings', img: 'https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=600&q=80', tag: 'Seamless' },
      { id: 'heavyweight-pullover-pl', name: 'Private Label Hoodie', img: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80', tag: '380gsm' },
    ],
    relatedCategories: ['gym-wear-manufacturer', 'activewear-manufacturer-china', 'sports-bra-manufacturer'],
    ctaText: 'Start Your Private Label Line',
  },
  {
    slug: 'custom-hoodie-manufacturer',
    h1: 'Custom Hoodie Manufacturer — Design Your Own Hoodie From MOQ 50',
    metaTitle: 'Custom Hoodie Manufacturer | Design Your Own Hoodie, MOQ 50pcs',
    metaDesc: 'ClothReady is a custom hoodie manufacturer in China. Heavyweight fleece, embroidery, screen print, and private label. MOQ 50pcs, samples in 7-10 days.',
    intro: "ClothReady is a custom hoodie manufacturer helping streetwear, fitness, and lifestyle brands design and produce their own hoodie from scratch — fabric weight, fit, colorway, and branding, all built to your spec. We produce from a single reference photo or a full tech pack.",
    intro2: "Whether you want a heavyweight boxy streetwear hoodie or a lightweight zip-up for a fitness line, our factory in Dongguan handles pattern making, fabric sourcing, sampling, and bulk production in-house — with a minimum order of just 50 pieces per colorway to start.",
    keyPoints: [
      'MOQ 50 pieces per colorway',
      'Heavyweight French terry & fleece, 280–380gsm',
      'Embroidery, screen print, puff print, and patches',
      'Samples ready in 7–10 business days',
    ],
    whatWeMake: [
      { name: 'Pullover Hoodies', moq: '50 pcs/color' },
      { name: 'Zip-Up Hoodies', moq: '50 pcs/color' },
      { name: 'Oversized Boxy Hoodies', moq: '50 pcs/color' },
      { name: 'Cropped Hoodies', moq: '50 pcs/color' },
      { name: 'Heavyweight Crewneck Sweatshirts', moq: '50 pcs/color' },
    ],
    fabrics: [
      { name: 'French Terry', spec: '320–380gsm, brushed interior', use: 'Premium streetwear hoodies' },
      { name: 'Cotton/Poly Fleece', spec: '280–320gsm', use: 'Everyday hoodies, better price point' },
      { name: '100% Cotton Loopback', spec: '340gsm', use: 'Heavyweight, no-shrink hoodies' },
    ],
    pricing: standardPricing,
    process: standardProcess('hoodie'),
    why: [
      { title: 'Fabric Weight You Choose', desc: 'From 280gsm lightweight to 380gsm heavyweight French terry — we source the exact hand-feel and drape your design calls for.' },
      { title: 'Full Customization', desc: 'Embroidery, screen print, puff print, woven patches, drawcord color, and custom ribbing — every detail is configurable.' },
      { title: 'Low MOQ — Start at 50 Pcs', desc: 'Launch a new hoodie colorway or style without committing to a factory-minimum bulk run.' },
      { title: 'Fast Sampling', desc: 'Physical samples in 7–10 days so you can check fit, fabric weight, and print placement before bulk production.' },
    ],
    faqs: [
      { q: 'What is the MOQ for a custom hoodie?', a: '50 pieces per colorway. You can mix multiple sizes within that minimum.' },
      { q: 'What fabric weight is best for streetwear hoodies?', a: 'Most streetwear brands choose 320–380gsm French terry or fleece for a substantial, premium hand-feel.' },
      { q: 'Can I get embroidery and print on the same hoodie?', a: 'Yes, we regularly combine embroidered logos with screen-printed graphics or patches on a single garment.' },
      { q: 'Do you make oversized/boxy fit hoodies?', a: 'Yes, oversized and boxy drop-shoulder fits are one of our most requested styles for streetwear brands.' },
      { q: 'How long does a custom hoodie order take?', a: 'Sample: 7–10 business days. Bulk production: 25–35 business days after sample approval.' },
    ],
    products: [
      { id: 'heavyweight-pullover-2', name: 'Heavyweight Pullover Hoodie', img: 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80', tag: '380gsm' },
      { id: 'zipup-hoodie-2', name: 'Zip-Up Hoodie', img: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&q=80', tag: 'Custom' },
      { id: 'oversized-hoodie-2', name: 'Oversized Boxy Hoodie', img: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80', tag: 'Streetwear' },
      { id: 'cropped-hoodie-2', name: 'Cropped Hoodie', img: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&q=80', tag: 'MOQ 50' },
    ],
    relatedCategories: ['custom-hoodies-manufacturer', 'streetwear-manufacturer', 'low-moq-clothing-factory'],
    ctaText: 'Design Your Custom Hoodie',
  },
  {
    slug: 'low-moq-clothing-factory',
    h1: 'Low MOQ Clothing Factory — Start Production at 50 Pieces',
    metaTitle: 'Low MOQ Clothing Manufacturer | Start at 50pcs | ClothReady China',
    metaDesc: 'ClothReady is a low MOQ clothing factory in China — 50 pieces per style per color across activewear, streetwear, and casualwear. No overstock risk for new brands.',
    intro: 'ClothReady is a low MOQ clothing factory built specifically for brands that need to test a new style without ordering thousands of units. Our minimum order is 50 pieces per style per color across our entire product range — activewear, streetwear, hoodies, joggers, and tees.',
    intro2: "Most factories in China require 300–1000+ piece minimums, which is a real barrier for new and growing brands validating a design. We built our production line around smaller, flexible runs so you can launch, test the market, and reorder based on real demand — not guesswork.",
    keyPoints: [
      'MOQ 50 pieces per style per color, factory-wide',
      'No overstock risk when testing a new design',
      'Reorder in smaller batches as demand grows',
      'Same QC standard on 50 pieces as on 5,000',
    ],
    whatWeMake: [
      { name: 'Leggings & Activewear', moq: '50 pcs/color' },
      { name: 'Hoodies & Sweatshirts', moq: '50 pcs/color' },
      { name: 'T-Shirts & Tanks', moq: '50 pcs/color' },
      { name: 'Joggers & Track Pants', moq: '50 pcs/color' },
      { name: 'Sports Bras & Tops', moq: '50 pcs/color' },
      { name: 'Jackets & Outerwear', moq: '100 pcs/color' },
    ],
    fabrics: [
      { name: 'Nylon/Spandex (80/20)', spec: '4-way stretch, 200–230gsm', use: 'Leggings, sports bras, shorts' },
      { name: 'Cotton/Poly Fleece', spec: '280–320gsm', use: 'Hoodies, sweatshirts' },
      { name: '100% Cotton', spec: '160–220gsm', use: 'Tees, tanks' },
      { name: 'Ripstop Nylon', spec: '180–220gsm', use: 'Joggers, windbreakers' },
    ],
    pricing: standardPricing,
    process: standardProcess('your product'),
    why: [
      { title: 'Built for Small Runs', desc: "Unlike factories that treat 50-piece orders as an afterthought, our production line is planned around low-MOQ batches from the ground up." },
      { title: 'No Overstock Risk', desc: 'Test a design at 50 pieces, validate demand, then reorder — instead of tying up capital in a 500-piece bet.' },
      { title: 'Same QC at Any Volume', desc: 'Every order, large or small, goes through the same AQL 2.5 inspection standard before shipping.' },
      { title: 'Scales With You', desc: 'Start at 50 pieces per style; as your brand grows we scale bulk production to 5,000+ pieces with the same team and specs.' },
    ],
    faqs: [
      { q: 'Is 50 pieces really the minimum, or is that per color?', a: 'It is 50 pieces per style per color. A single style in 3 colors would total 150 pieces minimum.' },
      { q: 'Why do most factories require higher minimums?', a: 'Larger factories optimize for volume efficiency and often won\'t restructure a production line for small runs. We built our workflow specifically to make 50-piece runs cost-effective.' },
      { q: 'Does a low MOQ mean lower quality?', a: 'No — every order, regardless of size, goes through the same fabric testing and AQL 2.5 quality inspection before shipping.' },
      { q: 'Can I mix multiple styles to reach a bulk discount?', a: 'Yes, ask your account contact about combined-style order discounts once you\'re ordering 500+ total pieces across styles.' },
      { q: 'What happens after my first 50-piece order sells out?', a: "You reorder in the same low-MOQ batches, or scale up quantity — the same tech pack and fabric spec carry over, so quality stays consistent." },
    ],
    products: [
      { id: 'gym-training-tee-2', name: 'Performance Training Tee', img: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&q=80', tag: 'MOQ 50' },
      { id: 'tapered-jogger-2', name: 'Tapered Fleece Joggers', img: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=600&q=80', tag: 'MOQ 50' },
      { id: 'cropped-hoodie-3', name: 'Cropped Hoodie', img: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&q=80', tag: 'MOQ 50' },
      { id: 'boxy-tee-2', name: 'Boxy Drop-Shoulder Tee', img: 'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?w=600&q=80', tag: 'MOQ 50' },
    ],
    relatedCategories: ['activewear-manufacturer-china', 'custom-hoodie-manufacturer', 'streetwear-manufacturer'],
    ctaText: 'Start a Low MOQ Order',
  },
]

export function getSeoLandingPageBySlug(slug: string): Category | undefined {
  return SEO_LANDING_PAGES.find((c) => c.slug === slug)
}
